

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Redis__Connection: ${Redis__Connection}
      SendGrid_ApiKey: ${SendGrid_ApiKey}

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5434:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
