

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5433;Database=Ecommerce;Username=davud;Password=davud"
      Redis__Connection: "redis:6379"
      SendGrid_ApiKey: "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"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5434:5433"
    environment:
      POSTGRES_USER: davud
      POSTGRES_PASSWORD: davud
      POSTGRES_DB: Ecommerce

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
